name: Build & Release
run-name: Build & release `dockerfile-json`
on:
  create:
    tags:
      - v*
jobs:
  build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        os:
          - darwin
          - linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Compile for ${{matrix.os}} (${{matrix.arch}})
        env:
          GOOS: "${{matrix.os}}"
          GOARCH: "${{matrix.arch}}"
        run: make compress

      - name: Upload compiled archives
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: build/*.txz
          if-no-files-found: error
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: build/

      - uses: softprops/action-gh-release@v1
        with:
          files: build/release/*.txz
          generate_release_notes: true
